<a href="https://colab.research.google.com/github/Madhan-sukumar/Deep-Learning/blob/main/pytorch/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the pytorch
import torch

In [ ]:
#printing 1d empty tensor
x =torch.empty(1)
print(x)

#printting 2d tensor
y= torch.empty(2,3)
print(y)

#printing 3d tensor
z= torch.empty(2,2,3)
print(z)

tensor([-1.2047e+11])
tensor([[3.5952e-34, 0.0000e+00, 3.5945e-34],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
tensor([[[-2.5555e-09,  4.5893e-41, -2.5555e-09],
         [ 4.5893e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [ ]:
#creating tensor with rand like numpy
r = torch.rand(2,3)
print(r)

z=torch.zeros(3,4)
print(z)

o=torch.ones(2,2)
print(o)

tensor([[0.7777, 0.4061, 0.7375],
        [0.2450, 0.5271, 0.7091]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
#checking datatype and converting to other datatypes
print(o.dtype)

#converting the datatype
i = torch.ones(3,4,dtype=torch.int32)
print(i.dtype)


torch.float32
torch.int32


In [ ]:
#printing the size of tensor
print(i.size())

torch.Size([3, 4])


In [ ]:
#can create a tensor using list
t = torch.tensor([[1,2,3,4],[3,4,5,6]])
print(t)
print(t.size())

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])
torch.Size([2, 4])


## **ELEMENTWISE OPERATIONS**

**ELEMENTWISE ADDITION**

In [ ]:
#elementwise addition
x=torch.rand(3,3)
y=torch.rand(3,3)

#adding
z = x+y

#can also use function
a = torch.add(x,y)

#performing inplace operation
# underscore(_) will replace the original element based on operation
y.add_(x)

print(z)
print(a)
print(y)

tensor([[1.6700, 1.2241, 1.4246],
        [1.2725, 0.5430, 0.9492],
        [0.9833, 1.4406, 1.1465]])
tensor([[1.6700, 1.2241, 1.4246],
        [1.2725, 0.5430, 0.9492],
        [0.9833, 1.4406, 1.1465]])
tensor([[1.6700, 1.2241, 1.4246],
        [1.2725, 0.5430, 0.9492],
        [0.9833, 1.4406, 1.1465]])


**ELEMENTWISE SUBTRACTION**

In [ ]:
#elementwise subtraction
x=torch.rand(3,3)
y=torch.rand(3,3)

#subtraction
z = x-y

#can also use function
a = torch.sub(x,y)

#performing inplace operation
# underscore(_) will replace the original element based on operation
y.sub_(x)

print(z)
print(a)
print(y)

tensor([[ 0.4312,  0.0119,  0.8504],
        [ 0.0585, -0.0320, -0.5705],
        [ 0.1406,  0.1913, -0.0101]])
tensor([[ 0.4312,  0.0119,  0.8504],
        [ 0.0585, -0.0320, -0.5705],
        [ 0.1406,  0.1913, -0.0101]])
tensor([[-0.4312, -0.0119, -0.8504],
        [-0.0585,  0.0320,  0.5705],
        [-0.1406, -0.1913,  0.0101]])


can perform  elementwise operations for multiplication and division using mul() and div() functions

## **SLICING**

In [ ]:
z = torch.rand(4,4)
print(z)

tensor([[0.5380, 0.3598, 0.0413, 0.0158],
        [0.0055, 0.8586, 0.2714, 0.2628],
        [0.8949, 0.2461, 0.0072, 0.4298],
        [0.5487, 0.9834, 0.7098, 0.9035]])


In [ ]:
#printing first 2 rows
print(z[0:2])

#printing first 2 rows and last 2 cols
print(z[0:2,-2:])

#printing all rows and 1st two col
print(z[:,:2])

#printing all rows and last 2 cols
print(z[:,-2:])

#printing all row and last 1 col
print(z[:,-1])

tensor([[0.5380, 0.3598, 0.0413, 0.0158],
        [0.0055, 0.8586, 0.2714, 0.2628]])
tensor([[0.0413, 0.0158],
        [0.2714, 0.2628]])
tensor([[0.5380, 0.3598],
        [0.0055, 0.8586],
        [0.8949, 0.2461],
        [0.5487, 0.9834]])
tensor([[0.0413, 0.0158],
        [0.2714, 0.2628],
        [0.0072, 0.4298],
        [0.7098, 0.9035]])
tensor([0.0158, 0.2628, 0.4298, 0.9035])


In [ ]:
#can get the actual value of an element using item()
#item() only use for getting only one value
print(z[3,2].item())

0.7097703814506531


# **RESHAPING**

In [ ]:
#Reshaping can be done using view()
x=torch.rand(4,4)
print(x)

#converting to 1d vector
y =x.view(16)
print(y)

#converting by auto determination using given 1 dim by giving -1
z = x.view(-1,2)
print(z)

a = x.view(8,-1)
print(z)


tensor([[0.6019, 0.1217, 0.6372, 0.5851],
        [0.2870, 0.6197, 0.5236, 0.9709],
        [0.6318, 0.2729, 0.9992, 0.0630],
        [0.9483, 0.5276, 0.6713, 0.0040]])
tensor([0.6019, 0.1217, 0.6372, 0.5851, 0.2870, 0.6197, 0.5236, 0.9709, 0.6318,
        0.2729, 0.9992, 0.0630, 0.9483, 0.5276, 0.6713, 0.0040])
tensor([[0.6019, 0.1217],
        [0.6372, 0.5851],
        [0.2870, 0.6197],
        [0.5236, 0.9709],
        [0.6318, 0.2729],
        [0.9992, 0.0630],
        [0.9483, 0.5276],
        [0.6713, 0.0040]])
tensor([[0.6019, 0.1217],
        [0.6372, 0.5851],
        [0.2870, 0.6197],
        [0.5236, 0.9709],
        [0.6318, 0.2729],
        [0.9992, 0.0630],
        [0.9483, 0.5276],
        [0.6713, 0.0040]])


# **TENSOR TO NUMPY AND VICE VERSA**

In [ ]:
a= torch.ones(5)
print(type(a))

#converting tensor to numpy array
b = a.numpy()
print(type(b))

#converting numpy array to tensor
c = torch.from_numpy(b)
print(type(c))



<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
